INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('propiedad1', 'valor1');
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2022, 200);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2023, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Ford', 'A3', 2019, 400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Ford', 'A6', 2020, 500);