INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('propiedad1', 'valor1');
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2022, 200);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1_TDI', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2022, 200);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3_COUPE', 2023, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3_TFSI', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4_TFSI', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A5', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q2', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q3', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q3_TFSI', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q7', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q7_TFSI', 2000, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'S3_PERFORMANCE', 2001, 100);


INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('BMW', 'A3-COU', 2022, 100);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Chevrolet', 'A3-COU', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('BYD', 'A3-COU', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Chery', 'A3-COU', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Citroen', 'A3-COU', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Daewoo', 'A3-COU', 2022, 100);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Ford', 'A3', 2019, 400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Ford', 'A6', 2020, 500);