INSERT INTO CONFIGURATION (PROPIEDAD, VALOR) VALUES ('propiedad1', 'valor1');
-- Audi A1
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2000, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2001, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2002, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2004, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2005, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2006, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2007, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2008, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2009, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2010, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2011, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2012, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2013, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2015, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2016, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2017, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2018, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2019, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2020, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1', 2022, 1400);

-- Audi A1 TFSI
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A1_TDI', 2014, 1600);

--Audi A3
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2001, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2002, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2003, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2004, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2005, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2006, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2008, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2009, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2010, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2011, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2012, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2013, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2015, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2016, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2018, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2019, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2020, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2021, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3', 2022, 1400);

-- Audi A3 Cuope
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3_COUPE', 2009, 200);

-- Audi A3 Tfsi
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A3_TFSI', 2011, 1800);

--Audi A4
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2001, 1800);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2004, 1800);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2005, 1800);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2007, 1800);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2009, 1800);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2011, 1800);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2015, 1800);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2018, 1800);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4', 2019, 1800);

--Audi A4 Tfsi
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A4_TFSI', 2015, 1800);

--Audi A5
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A5', 2010, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'A5', 2010, 3200);

--Audi Q2
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q2', 2021, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q2', 2022, 1400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q2', 2023, 1400);

--Audi Q3
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q3', 2017, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q3', 2019, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q3', 2022, 2000);

--Audi Q3 Tfsi
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q3_TFSI', 2022, 1400);

-- Audi Q5
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2011, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2011, 3000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2011, 3200);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2012, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2012, 3000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2012, 3200);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2014, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2014, 3000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2014, 3200);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2015, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2015, 3000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2015, 3200);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2016, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2016, 3000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2016, 3200);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2021, 2000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2021, 3000);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q5', 2021, 3200);


INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q7', 2024, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'Q7_TFSI', 2000, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Audi', 'S3_PERFORMANCE', 2001, 100);


--INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('BMW', 'A3-COU', 2022, 100);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Chevrolet', 'A3-COU', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('BYD', 'A3-COU', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Chery', 'A3-COU', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Citroen', 'A3-COU', 2022, 100);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Daewoo', 'A3-COU', 2022, 100);

INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Ford', 'A3', 2019, 400);
INSERT INTO VEHICLE (BRAND, MODEL, VEHICLE_YEAR, CYLINDER_CAPACITY) VALUES ('Ford', 'A6', 2020, 500);

--------------------- CATEGORIES ---------------------------

INSERT INTO CATEGORY (CATEGORY_NAME)  VALUES ('Mantenimiento preventivo');
INSERT INTO CATEGORY (CATEGORY_NAME)  VALUES ('Reparación y reemplazo de piezas');
INSERT INTO CATEGORY (CATEGORY_NAME)  VALUES ('Inspección y evaluación');
INSERT INTO CATEGORY (CATEGORY_NAME)  VALUES ('Ajuste y equilibrio');

-------------------- ITEMS ------------------------

INSERT INTO ITEM (ITEM_NAME, SHORT_DESCRIPTION, TECHNICAL_DESCRIPTION, IMAGE, ITEM_VALUE, CURRENCY, DISCOUNT, TAX, AVAILABILITY, CATEGORY_ID) VALUES ('Cambio de correa de repartición', 'sd', 'td', 'im', 50000, 0, 0, 19, TRUE, 1);
INSERT INTO ITEM (ITEM_NAME, SHORT_DESCRIPTION, TECHNICAL_DESCRIPTION, IMAGE, ITEM_VALUE, CURRENCY, DISCOUNT, TAX, AVAILABILITY, CATEGORY_ID) VALUES ('Cambio de amortiguadores', 'sd', 'td', 'im', 50000, 0, 0, 19, TRUE, 1);
INSERT INTO ITEM (ITEM_NAME, SHORT_DESCRIPTION, TECHNICAL_DESCRIPTION, IMAGE, ITEM_VALUE, CURRENCY, DISCOUNT, TAX, AVAILABILITY, CATEGORY_ID) VALUES ('Cambios de aceite y filtros', 'sd', 'td', 'im', 50000, 0, 0, 19, TRUE, 1);
INSERT INTO ITEM (ITEM_NAME, SHORT_DESCRIPTION, TECHNICAL_DESCRIPTION, IMAGE, ITEM_VALUE, CURRENCY, DISCOUNT, TAX, AVAILABILITY, CATEGORY_ID) VALUES ('qwe', 'sd', 'td', 'im', 50000, 0, 0, 19, TRUE, 2);
INSERT INTO ITEM (ITEM_NAME, SHORT_DESCRIPTION, TECHNICAL_DESCRIPTION, IMAGE, ITEM_VALUE, CURRENCY, DISCOUNT, TAX, AVAILABILITY, CATEGORY_ID) VALUES ('rty', 'sd', 'td', 'im', 50000, 0, 0, 19, TRUE, 2);
INSERT INTO ITEM (ITEM_NAME, SHORT_DESCRIPTION, TECHNICAL_DESCRIPTION, IMAGE, ITEM_VALUE, CURRENCY, DISCOUNT, TAX, AVAILABILITY, CATEGORY_ID) VALUES ('uio', 'sd', 'td', 'im', 50000, 0, 0, 19, TRUE, 2);

--------------------- ITEM_VEHICLE --------------------

INSERT INTO ITEM_VEHICLE (ITEM_ID, VEHICLE_ID) VALUES (1, 1);
INSERT INTO ITEM_VEHICLE (ITEM_ID, VEHICLE_ID) VALUES (2, 1);
INSERT INTO ITEM_VEHICLE (ITEM_ID, VEHICLE_ID) VALUES (3, 1);
INSERT INTO ITEM_VEHICLE (ITEM_ID, VEHICLE_ID) VALUES (4, 1);
INSERT INTO ITEM_VEHICLE (ITEM_ID, VEHICLE_ID) VALUES (5, 1);
INSERT INTO ITEM_VEHICLE (ITEM_ID, VEHICLE_ID) VALUES (6, 1);